#!/bin/bash

# 12-19-2025: generated by convo

# Initialize an empty array for JSON output
json_output=()

# Get the list of Wi-Fi interfaces
wifi_interfaces=$(nmcli -t -f DEVICE,TYPE device | grep ':wifi' | cut -d':' -f1)

# Iterate over each Wi-Fi interface and check for local IP address
for interface in $wifi_interfaces; do
    # Get the local IP address for the interface
    local_ip=$(nmcli -g IP4.ADDRESS device show "$interface" | cut -d'/' -f1)

    # If a local IP is found, add to the array
    if [ -n "$local_ip" ]; then
        json_output+=("{\"$interface\": \"$local_ip\"}")
    fi
done

# Convert the array to a JSON object using jq
printf '%s\n' "${json_output[@]}" | jq -s 'add | {interfaces: .}'
